---
title: "Week1"
author: "sarah.robertson@ucd.ie"
editor: visual
---

```{r}
sessionInfo()
```

```{r}
install.packages("dplyr")
library("dplyr")
```

```{r}
install.packages("BiocManager")
library(BiocManager)
install("PeacoQC")
library(PeacoQC)
install.packages("remotes")
library(remotes)
install_github("hally166/flowSpectrum")
library(flowSpectrum)
install.packages("purrr")
library(purrr)
install("flowCore")
library(flowCore)
install("flowWorkspace")
library(flowWorkspace)
install.packages("stringr")
library(stringr)
install.packages("ggplot2")
library(ggplot2)
install("ggcyto")
library(ggcyto)
install.packages("tidyr")
library(tidyr)
install("openCyto")
library(openCyto)
install("FlowSOM")
library(FlowSOM)
install.packages("xml2")
library(xml2)
install_github("saeyslab/CytoNorm")
library(CytoNorm)
install.packages("lubridate")
library(lubridate)
install.packages("httr2")
library(httr2)
install("flowGate")
library(flowGate)
install.packages("devtools")
library(devtools)
install.packages("plotly")
library(plotly)
install_github("biosurf/cyCombine")
library(cyCombine)
BiocManager::install("CytoML")
library(CytoML)
install.packages("Rtsne")
library(Rtsne)
install.packages("uwot")
library(uwot)
```
